import Images from "./Images/Images";

const AllProductObjects = [
  {
    id: 1,
    image: Images.product1,
    title: "קשת בלונים ענקית",
    description: "קשת בלונים ענקית בצבעים רכים ונעימים לעין.",
    price: 1500,
    category: "7",
  },
  {
    id: 2,
    image: Images.product2,
    title: "מארז מתוקים ליום הולדת",
    description:
      "מארז מתוקים וייחודי ליום הולדת, עם מגוון פריטים שיעשו את היום עוד יותר מיוחד.",
    price: 250,
    category: "3",
  },
  {
    id: 3,
    image: Images.product3,
    title: "קשת בלונים מושלמת לחתונה",
    description: "קשת בלונים מושלמת לחתונה, בצבעים לבנים וכסף מזהם.",
    price: 2000,
    category: "2",
  },
  {
    id: 4,
    image: Images.product4,
    title: "מארז מתנות מפנק",
    description: "מארז מתנות מפנק עם מגוון מוצרים שיעשו לכם יום נעים ומפנק.",
    price: 180,
    category: "4",
  },
  {
    id: 5,
    image: Images.product5,
    title: "מתנה מיוחדת ללידה",
    description:
      "מתנה מיוחדת ללידה, עם מגוון פריטים שיעזרו לכם להתאושש ולהתחיל את ההורות בכיוון הנכון.",
    price: 300,
    category: "9",
  },
  {
    id: 6,
    image: Images.product6,
    title: "קשת בלונים עם פרחים",
    description: "קשת בלונים עם פרחים ועלים טבעיים, למראה טבעי ומיוחד.",
    price: 1800,
    category: "7",
  },
  {
    id: 7,
    image: Images.product7,
    title: "קשת בלונים מעוצבת",
    description: "קשת בלונים מעוצבת בצבעים ובגוונים שונים, לאירועים מיוחדים.",
    price: 1200,
    category: "7",
  },
  {
    id: 8,
    image: Images.product8,
    title: "מתנה מיוחדת ליום נישואין",
    description:
      "מתנה מיוחדת ליום הנישואין, עם מגוון פריטים שיספקו לכם את היום הזה בצורה הכי טובה.",
    price: 350,
    category: "8",
  },
  {
    id: 9,
    image: Images.product9,
    title: "מתנה מעוצבת ללידה",
    description:
      "מתנה מעוצבת ללידה, עם מגוון פריטים שיעזרו לכם להתאושש ולהתחיל את ההורות בצורה הכי טובה.",
    price: 280,
    category: "9",
  },
  {
    id: 10,
    image: Images.product10,
    title: "קשת בלונים לחתונה בגווני חום",
    description: "קשת בלונים מרהיבה לחתונה בגווני חום וזהב משולבים.",
    price: 2200,
    category: "8",
  },
  {
    id: 11,
    image: Images.product11,
    title: "מארז מתנה לאירועי חג",
    description: "מארז מתנה ייחודי ומיוחד לאירועי חג כמו פסח וחנוכה.",
    price: 350,
    category: "5",
  },
  {
    id: 12,
    image: Images.product12,
    title: "קשת בלונים בגווני פסטל",
    description: "קשת בלונים עם גווני פסטל נעימים לעין ומיוחדים.",
    price: 1200,
    category: "7",
  },
  {
    id: 13,
    image: Images.product13,
    title: "מארז מתנות למשרד",
    description:
      "מארז מתנות מפנק למשרד, עם מגוון מוצרים שיעזרו לכם להתאושש מיום עמוס ולהתחיל מחדש.",
    price: 400,
    category: "4",
  },
  {
    id: 14,
    image: Images.product14,
    title: "קשת בלונים ענקית ליום הולדת",
    description: "קשת בלונים ענקית ליום הולדת מרהיבה וייחודית.",
    price: 1800,
    category: "3",
  },
  {
    id: 15,
    image: Images.product15,
    title: "מארז מתנה לאמא החדשה",
    description:
      "מארז מתנה מיוחד לאמא החדשה, עם מגוון פריטים שיעזרו לה להתאושש ולהתחיל את המסע של ההורות בכיוון הנכון.",
    price: 320,
    category: "9",
  },
  {
    id: 16,
    image: Images.product16,
    title: "קשת בלונים בגווני סיני",
    description: "קשת בלונים בגווני סיני לאירועי מסיבה וקלאסיים.",
    price: 950,
    category: "7",
  },
  {
    id: 17,
    image: Images.product17,
    title: "מארז מתנות לחתונה",
    description:
      "מארז מתנות לחתונה עם מגוון מוצרים שיעזרו לזוג החתונה להתאושש ולצאת לדרך ביחד.",
    price: 650,
    category: "2",
  },
  {
    id: 18,
    image: Images.product18,
    title: "קשת בלונים ענקית לחתונה",
    description: "קשת בלונים ענקית לחתונה מרהיבה וייחודית.",
    price: 2200,
    category: "8",
  },
  {
    id: 19,
    image: Images.product19,
    title: "מארז מתנה יוקרתי לעסקים",
    description:
      "מארז מתנה יוקרתי לעסקים, עם מגוון מוצרים שיעזרו לכם להפנים את העסק בצורה מקצועית ואטרקטיבית.",
    price: 1200,
    category: "4",
  },
  {
    id: 20,
    image: Images.product20,
    title: "קשת בלונים עם פרחים",
    description: "קשת בלונים עם פרחים מיוחדים לאירועי חג וסיבובי שנה.",
    price: 850,
    category: "7",
  },
  {
    id: 21,
    image: Images.product21,
    title: "מתנת פרחים יפהפיות",
    description:
      "מתנת פרחים מפנקת ומיוחדת עם בקבוק יין טעים ואקססוריז נהדרים לחווית מתנה שלמה.",
    price: 280,
    category: "4",
  },
  {
    id: 22,
    image: Images.product22,
    title: "קשת בלונים לבנה ענקית",
    description: "קשת בלונים לבנה ענקית לאירועי חתונה ואירועים מיוחדים.",
    price: 1500,
    category: "2",
  },
  {
    id: 23,
    image: Images.product23,
    title: "מארז מתנה יוקרתי לחג",
    description:
      "מארז מתנה יוקרתי לחגים עם כל מה שצריך לחגוג בסגנון ובאופן יוקרתי.",
    price: 600,
    category: "5",
  },
  {
    id: 24,
    image: Images.product24,
    title: "קשת בלונים ורודה וסגולה",
    description:
      "קשת בלונים בגווני ורוד וסגול עם פרחים מתאימה לאירועי יום הולדת וחגים מיוחדים.",
    price: 1200,
    category: "3",
  },
  {
    id: 25,
    image: Images.product25,
    title: "מארז מתנה לילדים",
    description:
      "מארז מתנה לילדים עם מגוון צעצועים ומוצרי יצירה לימי החג ולכל מטרה אחרת.",
    price: 350,
    category: "6",
  },
  {
    id: 26,
    image: Images.product26,
    title: "קשת בלונים מתוקה ליום נישואין",
    description: "קשת בלונים מתוקה וייחודית לחגוג את יום הנישואין המיוחד שלכם.",
    price: 900,
    category: "8",
  },
  {
    id: 27,
    image: Images.product27,
    title: "מתנת פרחים מפנקת ליום הולדת",
    description: "מתנת פרחים מפנקת ויוקרתית לחגוג את יום הולדתם של יקיריכם.",
    price: 550,
    category: "3",
  },
  {
    id: 28,
    image: Images.product28,
    title: "קשת בלונים מפנקת לאירועי חג",
    description: "קשת בלונים מפנקת ומיוחדת לחגים כמו פסח וחנוכה.",
    price: 1500,
    category: "5",
  },
  {
    id: 29,
    image: Images.product29,
    title: "מארז מתנה מפנק לחתונה",
    description:
      "מארז מתנה מפנק ויוקרתי לחתונה, עם מגוון פריטים מושלמים ליום הגדול.",
    price: 800,
    category: "2",
  },
  {
    id: 30,
    image: Images.product30,
    title: "קשת בלונים צבעונית למסיבת ילדים",
    description: "קשת בלונים צבעונית ומשוגעת למסיבת ילדים של מלכות ומלכים.",
    price: 1200,
    category: "7",
  },
  {
    id: 31,
    image: Images.product31,
    title: "קשת ענקית לחתונה",
    description: "קשת בלונים ענקית ומרהיבה לחתונה מהממת.",
    price: 2000,
    category: "2",
  },
  {
    id: 32,
    image: Images.product32,
    title: "מארז מתנה לאירוע עסקי",
    description: "מארז מתנה מעוצב ומפנק לאירוע עסקי או לתקופת החגים במשרד.",
    price: 500,
    category: "4",
  },
  {
    id: 33,
    image: Images.product33,
    title: "קשת בלונים ליום נישואין",
    description: "קשת בלונים מרהיבה ומפנקת ליום הנישואין המיוחד שלכם.",
    price: 1500,
    category: "8",
  },
  {
    id: 34,
    image: Images.product34,
    title: "מארז מתנה למילוי פינת קפה",
    description: "מארז מתנה מפנק למילוי פינת הקפה שלכם במשרד או בבית.",
    price: 350,
    category: "4",
  },
  {
    id: 35,
    image: Images.product35,
    title: "קשת בלונים חגיגית לחג המולד",
    description: "קשת בלונים עם דוגמת חג המולד המיוחדה והמרהיבה.",
    price: 800,
    category: "5",
  },
  {
    id: 36,
    image: Images.product36,
    title: "מארז קיץ עם קשת בלונים",
    description:
      "מארז קיץ מפנק עם קשת בלונים עם גווני ירקרק ותכלת, ומגוון מתנות מתוקות וטעימות להנאתכם המלאה.",
    price: 450,
    category: "6",
  },
  {
    id: 37,
    image: Images.product37,
    title: "קשת בלונים לבר מצווה",
    description: "קשת בלונים מרהיבה בגווני כחול וכסף לבר מצווה מיוחד וייחודי.",
    price: 1300,
    category: "2",
  },
  {
    id: 38,
    image: Images.product38,
    title: "מתנת גיל הורד",
    description: "מתנת גיל הורד מפנקת ומיוחדת למי שאוהב בלונים ומתוקים.",
    price: 150,
    category: "4",
  },
  {
    id: 39,
    image: Images.product39,
    title: "מארז מתנה לכל המשפחה",
    description:
      "מארז מתנה משפחתי מפנק ומיוחד עם קשת בלונים מרהיבה ומגוון מתנות מתוקות לכל המשפחה ליהנות מהזמן המשותף.",
    price: 550,
    category: "6",
  },
  {
    id: 40,
    image: Images.product40,
    title: "קשת בלונים מסתובבת",
    description: "קשת בלונים מסתובבת מרהיבה ומפנקת לכל אירוע מיוחד.",
    price: 800,
    category: "7",
  },
  {
    id: 41,
    image: Images.product41,
    title: "מתנת הפעם הראשונה",
    description:
      "מתנה מיוחדת לזוג החדש, עם כלים לארגון ולתכנן את הפעם הראשונה משותפת.",
    price: 600,
    category: "8",
  },
  {
    id: 42,
    image: Images.product42,
    title: "קשת בלונים בצבעי זהב וכסף",
    description:
      "קשת בלונים מרהיבה ומפנקת בצבעי זהב וכסף, מתאימה לכל אירוע מיוחד.",
    price: 1500,
    category: "7",
  },
  {
    id: 43,
    image: Images.product43,
    title: "מארז מתנה ליום הולדת",
    description: "מארז מתנה מיוחד ליום הולדת עם מגוון מוצרים מתוקים ומרגשים.",
    price: 300,
    category: "3",
  },
  {
    id: 44,
    image: Images.product44,
    title: "מארז מתנה לכלה וחתן",
    description:
      "מארז מתנה מפנק לכלה וחתן, עם מגוון מוצרים לקבלת אורחים וערכה לחתונה מושלמת.",
    price: 1000,
    category: "2",
  },
  {
    id: 45,
    image: Images.product45,
    title: "קשת בלונים בגווני קיץ",
    description:
      "קשת בלונים מרהיבה ומפנקת בגווני קיץ נעימים לעין, מתאימה לכל אירוע מיוחד.",
    price: 1200,
    category: "7",
  },
  {
    id: 46,
    image: Images.product46,
    title: "מתנת יום הולדת קטנה",
    description: "מתנת יום הולדת קטנה ומקסימה שתשדרג כל מסיבת יום הולדת לטובה.",
    price: 150,
    category: "3",
  },
  {
    id: 47,
    image: Images.product47,
    title: "מתנת יום נישואין",
    description:
      "מתנה יפה ומרגשת לזוג המתחתן, לחגוג את האהבה והמעמד החשוב בחייהם.",
    price: 600,
    category: "8",
  },
  {
    id: 48,
    image: Images.product48,
    title: "קשת פרחים בגווני ורוד",
    description: "קשת פרחים בגווני ורוד מרהיב ומיוחד לכל אירוע מיוחד ומיוחד.",
    price: 1200,
    category: "7",
  },
  {
    id: 49,
    image: Images.product49,
    title: "מתנה מפנקת ליום הולדת",
    description:
      "מתנה מפנקת ליום הולדת עם מגוון מוצרים שיעזרו לך לחגוג את היום המיוחד כמו שצריך.",
    price: 450,
    category: "3",
  },
  {
    id: 50,
    image: Images.product50,
    title: "קופסת מתנה חגיגית",
    description: "קופסת מתנה חגיגית בעיצוב מיוחד לחגים ולאירועים מיוחדים.",
    price: 250,
    category: "6",
  },
];

export default AllProductObjects;
